### ISSUE TITLE
RFC: Split GraphiQL from the bundle

### ISSUE THREAD

**Issue by renatomefi** [overblog/GraphQLBundle#199]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes
| Version/Branch   | 0.10.0

## TODO
- [x] A bundle: https://github.com/overblog/GraphiQLBundle
- [x] Document the new bundle https://github.com/overblog/GraphiQLBundle/pull/6
- [x] Symfony Flex recipe for OverblogGraphiQLBundle https://github.com/symfony/recipes-contrib/pull/127
- [x] Remove support for graphiql on this repository #225
- [x] Document the change
- [x] Document also on MIGRATE-0.11.md
- [x] Update Symfony Flex recipe for OverblogGraphQLBundle:0.10: https://github.com/symfony/recipes-contrib/pull/123

## How to test
- create a new symfony project: `composer create-project "symfony/skeleton:^3.3" test-graphiql`
- add the repo in composer (there's no packagist yet):
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/renatomefi/OverblogGraphiQLBundle.git"
        }
    ],
```
- install the bundle: `composer require overblog/graphiql-bundle`
- register the route: `config/routes/dev/graphiql.yaml`:
```
overblog_graphiql:
    resource: "@OverblogGraphiQLBundle/Resources/config/routing.xml"
```
- Install the OverblogGraphQLBundle: `composer require overblog/graphql-bundle`
- For now (will be removed on 0.10) remove the graphiql route: `rm config/routes/dev/graphql_graphiql.yaml`
- Run your local server and access /graphiql
- In theory it's all configured and working :)
- You might have errors if you don't have a proper schema

## RFC

I was thinking about refactoring some part of the code bundle, when I did step into the `GraphiQLController` and saw an opportunity to use more DI instead of the container usage, this comes with a problem.
If I inject twig, when the SF app doesn`t have it we are going to have a compile error, and that might be common since SF flex doesn`t bring twig by default, and it`s only interesting when on development enviroment.

My idea was to somehow only enable the controller in case it's dev environment or if the graphiql route is enable, which is when it makes sense, but when I was thinking about it the idea of splitting the bundle sounded better.

The GraphiQL bundle would be configurable with:
- endpoint
- GraphiQL, react and fetch JS libraries versions

Some other notes:
- The default configuration would auto-wire to OverblogGraphQLBundle.
- It would also make possible to use it standalone
- And also possible to use it with other graphql php libraries
- A new flex recipe for only graphiql will be added
- This bundle will require Twig explicitly

Is this a viable idea?

**Comment by mcg-web** [comment]
Yes this look good to me. More the bundle get light more it will be easy to maintain...

**Comment by renatomefi** [comment]
I have a WIP here: https://github.com/renatomefi/OverblogGraphiQLBundle
Not working yet, please don't contribute yet since I'm changing the code all the time

**Comment by renatomefi** [comment]
Flex recipe for the GraphiQL bundle is working: symfony/recipes-contrib#127

- `composer create-project "symfony/skeleton:^3.3" flex-graphiql-recipe`
- Change your minimum stability to beta on `composer.json`
- `SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes-contrib/127 composer req --dev overblog/graphiql-bundle`
- `php -S 127.0.0.1:8000 -t public`
- http://127.0.0.1:8000/graphiql

Of course this is without GraphQLBundle so nothing to see, so you can proceed installing it as well :)

**Comment by mcg-web** [comment]
no need alpha to start trying this I think but yes we can add a date to release a alpha version, maybe we should add information directly on milestone?

**Comment by renatomefi** [comment]
Good idea, I'm closing this one then!

![https://media.giphy.com/media/l3vRaWnqG3gOZ8lsk/giphy.gif](https://media.giphy.com/media/l3vRaWnqG3gOZ8lsk/giphy.gif)
